### PR TITLE
Add tree-sitter-nix

### PR DESCRIPTION
**Pull request by fidgetingbits**
Note the only way I got this building in order to test was by using the other PR https://github.com/cursorless-dev/vscode-parse-tree/pull/64 

Also nix is not an official language listed in https://code.visualstudio.com/docs/languages/identifiers but it seems to show up as nix in vscode, which may be due to me having a nix extension installed(?). Not sure if this will preclude it from being usable or not. I didn't run into any errors opening a .nix file in the extension after building it, but didn't know what to test beyond that to see if anything was broken.

### CODE REVIEW

**Review by pokey — COMMENTED** [review]
Looks good, but we generally pin to git version rather than release version (see most other tree-sitter dependencies in this file). For example, tree-sitter-nix has had 70 commits to its main branch since it was last released 2 years ago 😅

**Comment by pokey** [comment]
> Ah ya good point, so just pick whatever the latest commit is at the time of adding basicslly?

yep!

**Comment by fidgetingbits** [comment]
Updated the version. I tried to rebase this branch to your latest commits and it seemed to screw up the PR to include your recent commit changes, so just forced back to original git version commit and will leave it as is for now.

**Review by pokey — APPROVED** [review]

**Review by pokey — APPROVED** [review]
Looks good!

**Pull request merged**
