### PR TITLE
fix the build

### PR DESCRIPTION
**Pull request by phillco**
The build is currently broken on both M1 and Intel for me because `make web-tree-sitter` does not work:

```
$ yarn
yarn install v1.22.19
warning ../../package.json: No license field
$ make web-tree-sitter
emcc: error: undefined exported symbol: "__ZNKSt3__220__vector_base_commonILb1EE20__throw_length_errorEv" [-Wundefined] [-Werror]
make: *** [vendor/web-tree-sitter/0.20.4/README.md] Error 1
error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

It turns out that @pokey's build is working because he has a previously compiled version of web-tree-sitter exists in that directory.

We want to eliminate this dependency (#32) but for now, a quick fix is to check in that precompiled version so that others can build the project in the interim.

```
$ yarn
yarn install v1.22.19
warning ../../package.json: No license field
$ make web-tree-sitter
make: Nothing to be done for `web-tree-sitter'.
[1/5] 🔍  Validating package.json...
warning parse-tree@0.21.0: The engine "vscode" appears to be invalid.
[2/5] 🔍  Resolving packages...
[3/5] 🚚  Fetching packages...
[4/5] 🔗  Linking dependencies...
[5/5] 🔨  Building fresh packages...
success Saved lockfile.
✨  Done in 42.40s.
```

### CODE REVIEW

**Comment by pokey** [comment]
@wenkokke any objections? Would be good to at least un-break the build until we migrate to published web-tree-sitter

**Comment by wenkokke** [comment]
Why wouldn’t we just move to the latest published version?

**Comment by wenkokke** [comment]
For reference, this isn’t a hack, but just running the actual web-tree-sitter build.

**Comment by wenkokke** [comment]
The error reported above comes from tree-sitter itself
https://github.com/tree-sitter/tree-sitter/blob/a882d0b036b0da23cde5caa1325089b4ca4750ba/lib/binding_web/exports.json#L8

**Comment by wenkokke** [comment]
> The build is currently broken on both M1 and Intel for me because `make web-tree-sitter` does not work:
> 
> ```
> $ yarn
> yarn install v1.22.19
> warning ../../package.json: No license field
> $ make web-tree-sitter
> emcc: error: undefined exported symbol: "__ZNKSt3__220__vector_base_commonILb1EE20__throw_length_errorEv" [-Wundefined] [-Werror]
> make: *** [vendor/web-tree-sitter/0.20.4/README.md] Error 1
> error Command failed with exit code 2.
> info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
> ```
> 
> It turns out that @pokey's build is working because he has a previously compiled version of web-tree-sitter exists in that directory.
> 
> We want to eliminate this dependency (#32) but for now, a quick fix is to check in that precompiled version so that others can build the project in the interim.
> 
> ```
> $ yarn
> yarn install v1.22.19
> warning ../../package.json: No license field
> $ make web-tree-sitter
> make: Nothing to be done for `web-tree-sitter'.
> [1/5] 🔍  Validating package.json...
> warning parse-tree@0.21.0: The engine "vscode" appears to be invalid.
> [2/5] 🔍  Resolving packages...
> [3/5] 🚚  Fetching packages...
> [4/5] 🔗  Linking dependencies...
> [5/5] 🔨  Building fresh packages...
> success Saved lockfile.
> ✨  Done in 42.40s.
> ```

You probably want to submit this as an error on the tree-sitter repository.

**Comment by wenkokke** [comment]
Possibly related:
https://github.com/taglib/taglib/issues/1032#issuecomment-964261133

**Comment by pokey** [comment]
Closing in favour of https://github.com/cursorless-dev/vscode-parse-tree/pull/68, which works for me on a fresh clone

**Pull request closed without merging**
