### PR TITLE
Add preliminary xaml support using html parser

### PR DESCRIPTION
**Pull request by fatalerrorx**

### CODE REVIEW

**Comment by pokey** [comment]
I'm not sure this PR or https://github.com/cursorless-dev/cursorless/pull/1229 are necessary.  When I open a `.xaml` file, VSCode automatically treats it as `xml`.  I do run into https://github.com/cursorless-dev/vscode-parse-tree/issues/49#issuecomment-1253042360 pretty quickly, but that's independent.  Is VSCode treating `.xaml` files as something other than `xml` for you?

**Comment by fatalerrorx** [comment]
Unfortunately for me it doesn't work. Saying take tag or take value gives me the error "Cannot read properties of undefined (reading 'apply')". I also can't use things like take inside.

**Comment by pokey** [comment]
@fatalerrorx yes that's likely due to https://github.com/cursorless-dev/vscode-parse-tree/issues/49#issuecomment-1247538465.  Xaml tends to use longer tag names, and for whatever reason our html parser barfs on those https://github.com/tree-sitter/tree-sitter-html/issues/30 / https://github.com/cursorless-dev/vscode-parse-tree/issues/49

**Comment by fatalerrorx** [comment]
@pokey Yes I realized that after I made the comment.

**Pull request closed without merging**
