### PR TITLE
add: dart language compatibility

### PR DESCRIPTION
**Pull request by sonnyvesali**
Hey @pokey, I Followed the steps as best as I could for adding support for new programming language. Let me know if there are any changes I need to make to get this merged. Thanks!

### CODE REVIEW

**Comment by sonnyvesali** [comment]
migrated to `serenade.ai` already has lang support for dart ✌🏽

**Comment by pokey** [comment]
Sounds good; lmk if you come back and I'd be happy to help push this out. Best of luck with Serenade!

**Comment by sonnyvesali** [comment]
I take that back, the controls are not close to what I need, this is way better.

Please merge this whenever possible  @pokey

**Comment by pokey** [comment]
Welcome back ☺️

I'm on vacation this week but will merge and cut a release when I'm back

**Comment by pokey** [comment]
Just pushed release, will be out in parse tree extension version 0.32.0, which should be out in the next few minutes

**Comment by pokey** [comment]
Feel free to into a meet-up (see [cal](https://tinyurl.com/talon-events)) if you want some help with the remainder of https://www.cursorless.org/docs/contributing/adding-a-new-language/. Ping us first though so we can find a time to make sure one of the Cursorless maintainers can join

**Comment by sonnyvesali** [comment]
Hi @pokey just following up, I'm using it in vscode (made sure version was updated) in dart files and I still get the `dart language not implemented yet` when I try to use a smart scope, anything I might be missing or reason why it's not working?

**Comment by pokey** [comment]
You've done step 1 of adding a language. See [the guide](https://www.cursorless.org/docs/contributing/adding-a-new-language/) for how to do the remaining steps, and feel free to drop into a meetup if you want help

**Pull request merged**
